# Custom deployment to GitHub Pages so we can use a self-hosted runner

name: Deploy MKDocs

on:
  push:
    paths: ["docs/**"]
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

jobs:
  build:
    name: Build and deploy MKDocs
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-v1-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install pip --upgrade && pip install -r requirements.txt
      - name: Build and deploy MKDocs
        run: mkdocs gh-deploy --force
